name: CI
on:
  pull_request:
    branch:
      - main
      - develop
  push:
    branch:
      - main
      - develop

jobs:
  widget_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      name: check import sort
      - run: flutter pub run import_sorter:main --no-comments --exit-if-changed
      name: check code format
      - run: flutter format --set-exit-if-changed .
      name: analyze lint
      - run: flutter analyze
      name: test
      - run: flutter test
      name: integration test
      - run: flutter test integration_test/search_test.dart